<?php
require 'Conexion.php';
$db = Conexion::getConnect();
$stmt = $db->query("SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_NAME = 'instructor'");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
